CREATE TABLE Doctors (
	doc_id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	initial VARCHAR(250) NOT NULL,
	firstname VARCHAR(250) NOT NULL,
	lastname VARCHAR(250) NOT NULL,
	room_name VARCHAR(250) NOT NULL UNIQUE,
	email VARCHAR(250) NOT NULL,
	password VARCHAR(250) NOT NULL,
	provider INT(5) NOT NULL,
	status INT(5) DEFAULT 0    
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



-- crete pateinet table



CREATE TABLE Patient (
	patient_id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	patient_name VARCHAR(250) NOT NULL,
	d_id INT(11) NOT NULL,
	url VARCHAR(250) NOT NULL UNIQUE,
	status INT(5) DEFAULT 0,    
	b_name VARCHAR(250) DEFAULT NULL,
	b_verion VARCHAR(250) DEFAULT NULL,
	p_form VARCHAR(250) DEFAULT NULL,
	FOREIGN KEY (d_id) REFERENCES Doctors(doc_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- create table time

CREATE TABLE timing (
	call_id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	p_id INT(11) NOT NULL,
	d_id INT(11) NOT NULL,
	call_start TEXT,
	call_end TEXT NULL,
	FOREIGN KEY (d_id) REFERENCES Doctors(doc_id),
	FOREIGN KEY (p_id) REFERENCES Patient(patient_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE personal (
	p_id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	dsp_name VARCHAR(250) NOT NULL,
	special VARCHAR(250) NOT NULL,
	position VARCHAR(250) NOT NULL,
	NPI VARCHAR(250) NOT NULL,
	provider VARCHAR(250) NOT NULL,
	language VARCHAR(250) NOT NULL,
	d_id INT(11) NOT NULL UNIQUE,
	FOREIGN KEY (d_id) REFERENCES Doctors(doc_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- room_setting

CREATE TABLE room (
	r_id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	profile_pic VARCHAR(250) NOT NULL,
	d_name VARCHAR(250) NOT NULL,
	cam_pre VARCHAR(250) NOT NULL,
	room_pass VARCHAR(250) NOT NULL,
	c_term VARCHAR(250) NOT NULL,
	d_id INT(11) NOT NULL UNIQUE,
	FOREIGN KEY (d_id) REFERENCES Doctors(doc_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



CREATE TABLE msgs (
	m_id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
	msg VARCHAR(250) NOT NULL,
	d_id INT(11) NOT NULL,
	url VARCHAR(250) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


